### ISSUE TITLE
Adjusting firmware for custom splitter board

### ISSUE THREAD

**Issue by ChunkBuster** [luc-github/Repetier-Firmware-4-Davinci#311]
I managed to burn out the board that splits the ribbon cable by being a total Gibbon, and i've created a replacement one. Everything works as expected... Everything except for the Extruder temperatures reported by the firmware. As the old board had resistors, I'm sure that there is some offset that you added to the firmware to compensate for this, but I can't find it. Where is this offset in the firmware? 

Further, is there any chance of this being possibly added as a flag in the configuration? I'm sure that I'm not the only one that has either burned out the board or removed it as it serves no real purpose if you intend to replace the hotends, filament sensors, extruders, or essentially any part of the printer.

**Comment by luc-github** [comment]
Hi what printer have you ? 1.0/2.0 or 1.0a/2.0a/AiO, boards are differents

There is no offset but a custom themistor table because stock thermistor is unknown and looks different between board generations - I am guessing you are talking about the daughter board where Jam sensor(s) (not currently used), filament sensor(s), fan(s), heat extruder(s) and thermistor(s) are connected

**Comment by luc-github** [comment]
closing as no update
